language: python
matrix:
  include:
    - python: "3.7"
    - python: "3.8"
install:
  - pip install -e '.[testing]'
script:
  - black --check .
  - pytest --cov=viper
after_success:
  - bash <(curl -s https://codecov.io/bash)
